### ISSUE TITLE
Add title attributes to buttons

### ISSUE THREAD

**Issue by guerda** [alt-text-org/my.alt-text.org#12]
**Describe the bug**
The buttons are not yet very descriptive, what they are doing. It would be great if the buttons have mouseover titles to describe what they will do if you press it.
Especially buttons like "👯" are very undescriptive as of now.

**To Reproduce**
1. Go to the page
2. Hover over a button

**Expected behavior**
A description what happens should occur as a mouse over

**Additional context**

Examples:

* https://github.com/alt-text-org/my.alt-text.org/blob/main/index.html#L52 could include `title="Open the help dialog"`
* https://github.com/alt-text-org/my.alt-text.org/blob/main/index.html#L68C14-L68C14 could include `title="Toggle search results"`
etc.

**Comment by hkolbeck** [comment]
Done, will be released with the UI change in the coming days.
